spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.171.51/sc3?useSSL=false
    username: root
    password: 123456
  application:
    name: user-service
mybatis:
  type-aliases-package: com.zdf.user.entities
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: MySpringCloud-user-service03-9093
    prefer-ip-address: true